apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemon-pod
  labels:
    app: jenkins-pod
spec:
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:      
        app: jenkins
    spec:
      containers:
        - name: jenkins     
          image: jenkins/jenkins:lts 
