apiVersion: v1
kind: Service
metadata:
  name: jenkins-nlb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "instance"
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer       
  selector:                      #(To link service and Pod)        
    app: match                 #(name of the pod we create)  
  ports:
    - name: pod-port
      protocol: TCP              #(which kind of port we will use)              
      port: 80                  #(mapped to service) or (port with which we access the service)
      targetPort: 8080           #(mapped to container)
