apiVersion: v1
kind: Pod
metadata:
  name: node-selector-pod1
  labels:
    app: jenkins
spec:
  containers:
    - name: jenkins-pod
      image: jenkins/jenkins:lts
  affinity:
    nodeAffinity:   
      requiredDuringSchedulingIgnoredDuringExecution:     
        nodeSelectorTerms:
          - matchExpressions:
              - key: size
                operator: In
                values:
                  - worker-node-1
