apiVersion: v1
kind: Service
metadata:
  name: cluster-ip
spec:
  selector:                      #(To link service and Pod)        
    app: match                   #(name of the pod we created)  
  ports:
    - name: first-port
      protocol: TCP              #(which kind of port we will use)              
      port: 8090                 #(mapped to service) or (port with which we access the service)
      targetPort: 8080           #(mapped to container)
