apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
    - name: secret-container
      image: jenkins/jenkins:lts
      volumeMounts:
        - mountPath: /secrets
          name: secret-volume         #name of the volume to refernce
  volumes:
    - name: secret-volume             #name of volume
      secret:
       secretName: my-secrets              #name of the secret created
